### ISSUE TITLE
2.0.1 breaks username vs uid

### ISSUE THREAD

**Issue by TD-4242** [chef-cookbooks/users#125]
After testing 2.0.1 on existing systems the change from username to uid breaks installed users.  I now get unknown user 5000 errors when a user with uid 5000 has existed for over a year.

**Comment by richardowen** [comment]
I think this has also broken the creation of the .ssh directory. If uid isn't specified in the user's data bag, it doesn't have a user for the .ssh directory so creates it with owner root. Then because the permissions are 0700 you can't ssh in as that user as it can't access the authorized_keys file.

This happened in commit 82e8e60.

**Comment by iennae** [comment]
Thanks, will take a look.

**Comment by Chili-Man** [comment]
I'm running into this issue as well, where the .ssh directory is owned by root instead of the user

**Comment by dzabel** [comment]
+1

**Comment by sigil66** [comment]
same. .ssh suddenly root owned

**Comment by iennae** [comment]
Ok, so after debugging a bit, have identified 2 implicit assumptions about user data bags objects:

1. that a user databag object has UID specified as an int versus a string
2. that a user databag object has a UID specified at all 

The change from username to uid was made due to Mac OS X user creation issues. This uncovered some false assumptions that I had about databag objects. Looking into resolving both of these issues. Thanks for the report folks!

**Comment by iennae** [comment]
also 

3. if a user databag object uid is set to equal the username, that would also cause .ssh to be owned by root.

**Comment by rumdawgg** [comment]
Also seeing the .ssh and authorized_keys owned by root on Debian and CentOS.

**Comment by iennae** [comment]
Hey folks, let me know how 2.0.2 works for you and if it fixes the problem. Thanks!

**Comment by rumdawgg** [comment]
It works! And it corrected the .ssh directories with incorrect ownership!

**Comment by iennae** [comment]
Awesome. Thanks for the confirmation.
