### ISSUE TITLE
What's up with [:remove, :create] ?

### ISSUE THREAD

**Issue by jblaine** [chef-cookbooks/users#134]
The README repeats the 'action [:remove, :create]' pattern enough to make me think that's a pattern to follow, but also suggests that the users_manage resource is not idempotent?

That is, is 'action [:remove, :create]' actually deleting account definitions in /etc/passwd and /etc/shadow and then recreating them when using that pattern? That seems really bad if only that it's causing a race condition between Chef runs and people trying to login.

Just trying to understand...

**Comment by iennae** [comment]
@jblaine Thank you for bringing this issue up. The problem is that there are some implicit usages of this cookbook that lead to some less than quality experiences. We don't recommend the pattern of remove, create. I'll be updating the documentation to clarify this. The create is not an "create and update" within this cookbook. So the idea is that if you need to update, you would do remove and create. This leads to less than quality experiences if you don't hard code UIDs. Also unexpected behaviors can occur if a service account is deleted and created while the service is running.

**Comment by nkadel-skyhook** [comment]
The most problematic behavior is not when the service is running: it's when the gid is changed while a service is running with that username, such as nginx, nagios, nrpe, or apache. If they uid is in use, the attempt to delete the user will fail on most systems.

However, if the daemon is inactive and the account is deleted and restored with a different uid, or the uid reset, that can indeed cause profound issues.

**Comment by nkadel-skyhook** [comment]
The ":remove, :create" options in recipes are what the recipe permits the data bag to do. Different individual data bags may individually select one option or  the other. This can be especially handy when one databag, such as "users", has standard accounts, and the other, called "users-dev", has a bunch of JSON files that may need to be activated or deleted in a particular environment. Set the named databag to "users" and you get default accounts, set the designated databag to "users-dev" and you get developer accounts, and can use a distinct data bag called "nkadel" in each to add, or delete, the particular user account.

Personally, I'd have really preferred roles to designate lists of usernames and uids and other relevant hashed configurations, with encrypted databags reserved for SSH keys or passwords. But that's more of a rewrite than I could personally do.

**Comment by iennae** [comment]
@nkadel-skyhook, Thanks for the additional information and nuance about this issue. Thanks!

**Comment by jblaine** [comment]
Yes, thank you all for the detailed replies.
