### ISSUE TITLE
How to allow non_unique users?

### ISSUE THREAD

**Issue by jblaine** [chef-cookbooks/users#136]
How does one make use of various `user` resource properties, such as `non_unique` ?

>The user resource has the following properties:
> ...
>non_unique
>
> Ruby Types: TrueClass, FalseClass
> Create a duplicate (non-unique) user account.

**Comment by iennae** [comment]
Currently as this cookbook is written, it is not possible. It could be added but I think that this probably needs to be rewritten so that if the user resource changes parameters that we aren't trying to rewrite the resources in this cookbook each time. If you need this or other attributes that are not currently available, I recommend forking and adding and sharing your changes.
